//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from NSPredicate.g4 by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="INSPredicateListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public partial class NSPredicateBaseListener : INSPredicateListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.PredicateNot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredicateNot([NotNull] NSPredicateParser.PredicateNotContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.PredicateNot"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredicateNot([NotNull] NSPredicateParser.PredicateNotContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.PredicateTrue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredicateTrue([NotNull] NSPredicateParser.PredicateTrueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.PredicateTrue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredicateTrue([NotNull] NSPredicateParser.PredicateTrueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.PredicateComparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredicateComparison([NotNull] NSPredicateParser.PredicateComparisonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.PredicateComparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredicateComparison([NotNull] NSPredicateParser.PredicateComparisonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.PredicateOr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredicateOr([NotNull] NSPredicateParser.PredicateOrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.PredicateOr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredicateOr([NotNull] NSPredicateParser.PredicateOrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.PredicateParens"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredicateParens([NotNull] NSPredicateParser.PredicateParensContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.PredicateParens"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredicateParens([NotNull] NSPredicateParser.PredicateParensContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.PredicateFalse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredicateFalse([NotNull] NSPredicateParser.PredicateFalseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.PredicateFalse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredicateFalse([NotNull] NSPredicateParser.PredicateFalseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.PredicateAnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredicateAnd([NotNull] NSPredicateParser.PredicateAndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.PredicateAnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredicateAnd([NotNull] NSPredicateParser.PredicateAndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.ComparisonPredicateUnqualified"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparisonPredicateUnqualified([NotNull] NSPredicateParser.ComparisonPredicateUnqualifiedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.ComparisonPredicateUnqualified"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparisonPredicateUnqualified([NotNull] NSPredicateParser.ComparisonPredicateUnqualifiedContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.ComparisonPredicateAny"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparisonPredicateAny([NotNull] NSPredicateParser.ComparisonPredicateAnyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.ComparisonPredicateAny"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparisonPredicateAny([NotNull] NSPredicateParser.ComparisonPredicateAnyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.ComparisonPredicateSome"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparisonPredicateSome([NotNull] NSPredicateParser.ComparisonPredicateSomeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.ComparisonPredicateSome"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparisonPredicateSome([NotNull] NSPredicateParser.ComparisonPredicateSomeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.ComparisonPredicateAll"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparisonPredicateAll([NotNull] NSPredicateParser.ComparisonPredicateAllContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.ComparisonPredicateAll"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparisonPredicateAll([NotNull] NSPredicateParser.ComparisonPredicateAllContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.ComparisonPredicateNone"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparisonPredicateNone([NotNull] NSPredicateParser.ComparisonPredicateNoneContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.ComparisonPredicateNone"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparisonPredicateNone([NotNull] NSPredicateParser.ComparisonPredicateNoneContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.UnqualifiedComparisonPredicate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnqualifiedComparisonPredicate([NotNull] NSPredicateParser.UnqualifiedComparisonPredicateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.UnqualifiedComparisonPredicate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnqualifiedComparisonPredicate([NotNull] NSPredicateParser.UnqualifiedComparisonPredicateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.OperatorBetween"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorBetween([NotNull] NSPredicateParser.OperatorBetweenContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.OperatorBetween"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorBetween([NotNull] NSPredicateParser.OperatorBetweenContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.OperatorOptions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorOptions([NotNull] NSPredicateParser.OperatorOptionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.OperatorOptions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorOptions([NotNull] NSPredicateParser.OperatorOptionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.OperatorOptionsBare"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorOptionsBare([NotNull] NSPredicateParser.OperatorOptionsBareContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.OperatorOptionsBare"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorOptionsBare([NotNull] NSPredicateParser.OperatorOptionsBareContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.OperatorOptionsSpecified"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorOptionsSpecified([NotNull] NSPredicateParser.OperatorOptionsSpecifiedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.OperatorOptionsSpecified"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorOptionsSpecified([NotNull] NSPredicateParser.OperatorOptionsSpecifiedContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.OpEqualTo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpEqualTo([NotNull] NSPredicateParser.OpEqualToContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.OpEqualTo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpEqualTo([NotNull] NSPredicateParser.OpEqualToContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.OpNotEqualTo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpNotEqualTo([NotNull] NSPredicateParser.OpNotEqualToContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.OpNotEqualTo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpNotEqualTo([NotNull] NSPredicateParser.OpNotEqualToContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.OpLessThan"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpLessThan([NotNull] NSPredicateParser.OpLessThanContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.OpLessThan"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpLessThan([NotNull] NSPredicateParser.OpLessThanContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.OpGreaterThan"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpGreaterThan([NotNull] NSPredicateParser.OpGreaterThanContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.OpGreaterThan"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpGreaterThan([NotNull] NSPredicateParser.OpGreaterThanContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.OpLessThanOrEqualTo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpLessThanOrEqualTo([NotNull] NSPredicateParser.OpLessThanOrEqualToContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.OpLessThanOrEqualTo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpLessThanOrEqualTo([NotNull] NSPredicateParser.OpLessThanOrEqualToContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.OpGreaterThanOrEqualTo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpGreaterThanOrEqualTo([NotNull] NSPredicateParser.OpGreaterThanOrEqualToContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.OpGreaterThanOrEqualTo"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpGreaterThanOrEqualTo([NotNull] NSPredicateParser.OpGreaterThanOrEqualToContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.OpContains"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpContains([NotNull] NSPredicateParser.OpContainsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.OpContains"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpContains([NotNull] NSPredicateParser.OpContainsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.OpIn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpIn([NotNull] NSPredicateParser.OpInContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.OpIn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpIn([NotNull] NSPredicateParser.OpInContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.OpBeginsWith"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpBeginsWith([NotNull] NSPredicateParser.OpBeginsWithContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.OpBeginsWith"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpBeginsWith([NotNull] NSPredicateParser.OpBeginsWithContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.OpEndsWith"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpEndsWith([NotNull] NSPredicateParser.OpEndsWithContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.OpEndsWith"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpEndsWith([NotNull] NSPredicateParser.OpEndsWithContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.OpLike"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpLike([NotNull] NSPredicateParser.OpLikeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.OpLike"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpLike([NotNull] NSPredicateParser.OpLikeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.OpMatches"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpMatches([NotNull] NSPredicateParser.OpMatchesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.OpMatches"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpMatches([NotNull] NSPredicateParser.OpMatchesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.ExprMult"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprMult([NotNull] NSPredicateParser.ExprMultContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.ExprMult"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprMult([NotNull] NSPredicateParser.ExprMultContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.ExprIndex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprIndex([NotNull] NSPredicateParser.ExprIndexContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.ExprIndex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprIndex([NotNull] NSPredicateParser.ExprIndexContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.ExprParens"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprParens([NotNull] NSPredicateParser.ExprParensContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.ExprParens"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprParens([NotNull] NSPredicateParser.ExprParensContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.ExprSubquery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprSubquery([NotNull] NSPredicateParser.ExprSubqueryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.ExprSubquery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprSubquery([NotNull] NSPredicateParser.ExprSubqueryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.ExprConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprConstant([NotNull] NSPredicateParser.ExprConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.ExprConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprConstant([NotNull] NSPredicateParser.ExprConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.ExprPower"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprPower([NotNull] NSPredicateParser.ExprPowerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.ExprPower"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprPower([NotNull] NSPredicateParser.ExprPowerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.ExprNoArgFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprNoArgFunction([NotNull] NSPredicateParser.ExprNoArgFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.ExprNoArgFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprNoArgFunction([NotNull] NSPredicateParser.ExprNoArgFunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.ExprDiv"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprDiv([NotNull] NSPredicateParser.ExprDivContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.ExprDiv"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprDiv([NotNull] NSPredicateParser.ExprDivContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.ExprKeypathBinaryExpressions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprKeypathBinaryExpressions([NotNull] NSPredicateParser.ExprKeypathBinaryExpressionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.ExprKeypathBinaryExpressions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprKeypathBinaryExpressions([NotNull] NSPredicateParser.ExprKeypathBinaryExpressionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.ExprKeypathIdentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprKeypathIdentifier([NotNull] NSPredicateParser.ExprKeypathIdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.ExprKeypathIdentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprKeypathIdentifier([NotNull] NSPredicateParser.ExprKeypathIdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.ExprArgFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprArgFunction([NotNull] NSPredicateParser.ExprArgFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.ExprArgFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprArgFunction([NotNull] NSPredicateParser.ExprArgFunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.ExprKeypathAtIdentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprKeypathAtIdentifier([NotNull] NSPredicateParser.ExprKeypathAtIdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.ExprKeypathAtIdentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprKeypathAtIdentifier([NotNull] NSPredicateParser.ExprKeypathAtIdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.ExprSub"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprSub([NotNull] NSPredicateParser.ExprSubContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.ExprSub"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprSub([NotNull] NSPredicateParser.ExprSubContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.ExprAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprAssign([NotNull] NSPredicateParser.ExprAssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.ExprAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprAssign([NotNull] NSPredicateParser.ExprAssignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.ExprUnaryMinus"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprUnaryMinus([NotNull] NSPredicateParser.ExprUnaryMinusContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.ExprUnaryMinus"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprUnaryMinus([NotNull] NSPredicateParser.ExprUnaryMinusContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.ExprAdd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprAdd([NotNull] NSPredicateParser.ExprAddContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.ExprAdd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprAdd([NotNull] NSPredicateParser.ExprAddContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.IndexExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndexExpr([NotNull] NSPredicateParser.IndexExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.IndexExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndexExpr([NotNull] NSPredicateParser.IndexExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.IndexFirst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndexFirst([NotNull] NSPredicateParser.IndexFirstContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.IndexFirst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndexFirst([NotNull] NSPredicateParser.IndexFirstContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.IndexLast"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndexLast([NotNull] NSPredicateParser.IndexLastContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.IndexLast"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndexLast([NotNull] NSPredicateParser.IndexLastContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.IndexSize"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndexSize([NotNull] NSPredicateParser.IndexSizeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.IndexSize"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndexSize([NotNull] NSPredicateParser.IndexSizeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.ValueString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueString([NotNull] NSPredicateParser.ValueStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.ValueString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueString([NotNull] NSPredicateParser.ValueStringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.ValueNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueNumber([NotNull] NSPredicateParser.ValueNumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.ValueNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueNumber([NotNull] NSPredicateParser.ValueNumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.ValueFormat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueFormat([NotNull] NSPredicateParser.ValueFormatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.ValueFormat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueFormat([NotNull] NSPredicateParser.ValueFormatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.ValueVariable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueVariable([NotNull] NSPredicateParser.ValueVariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.ValueVariable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueVariable([NotNull] NSPredicateParser.ValueVariableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.ValueNull"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueNull([NotNull] NSPredicateParser.ValueNullContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.ValueNull"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueNull([NotNull] NSPredicateParser.ValueNullContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.ValueTrue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueTrue([NotNull] NSPredicateParser.ValueTrueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.ValueTrue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueTrue([NotNull] NSPredicateParser.ValueTrueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.ValueFalse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueFalse([NotNull] NSPredicateParser.ValueFalseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.ValueFalse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueFalse([NotNull] NSPredicateParser.ValueFalseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.ValueSelf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueSelf([NotNull] NSPredicateParser.ValueSelfContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.ValueSelf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueSelf([NotNull] NSPredicateParser.ValueSelfContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.ValueEmptyAggregate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueEmptyAggregate([NotNull] NSPredicateParser.ValueEmptyAggregateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.ValueEmptyAggregate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueEmptyAggregate([NotNull] NSPredicateParser.ValueEmptyAggregateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.ValueAggregate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValueAggregate([NotNull] NSPredicateParser.ValueAggregateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.ValueAggregate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValueAggregate([NotNull] NSPredicateParser.ValueAggregateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.ExprListAccum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprListAccum([NotNull] NSPredicateParser.ExprListAccumContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.ExprListAccum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprListAccum([NotNull] NSPredicateParser.ExprListAccumContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.ExprListSingle"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprListSingle([NotNull] NSPredicateParser.ExprListSingleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.ExprListSingle"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprListSingle([NotNull] NSPredicateParser.ExprListSingleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NSPredicateParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable([NotNull] NSPredicateParser.VariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NSPredicateParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable([NotNull] NSPredicateParser.VariableContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
